name: I14Y Test Harvester ABN

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 min
  workflow_dispatch:  # Allows manual triggering

jobs:
  harvest-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run harvester script
      env:
        CLIENT_KEY: ${{ secrets.CLIENT_KEY }}
        CLIENT_KEY_SECRET: ${{ secrets.CLIENT_KEY_SECRET }}
        GET_ENDPOINT_FROM: ${{ secrets.GET_ENDPOINT_FROM }}
        GET_ENDPOINT_TO: ${{ secrets.GET_ENDPOINT_TO }}
        POST_ENDPOINT: ${{ secrets.POST_ENDPOINT }}
      run: python scripts/i14y-test/harvester.py

    - name: Upload log
      uses: actions/upload-artifact@v4
      with:
        name: harvest-log
        path: harvest_log.txt
